services:
  auth:
    build: ./auth
    ports:
      - "8000:5000"
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DB_HOST=postgres_db
      - DB_NAME=meubanco
      - DB_USER=usuario
      - DB_PASSWORD=senha
    develop:
      watch:
        - action: sync
          path: ./auth
          target: /code
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  user:
    build: ./user
    ports:
      - "8001:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DB_HOST=postgres_db
      - DB_NAME=meubanco
      - DB_USER=usuario
      - DB_PASSWORD=senha
    develop:
      watch:
        - action: sync
          path: ./user
          target: /code
  curso_conteudo:
    build: ./curso_conteudo
    ports:
      - "8002:5000"
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DB_HOST=postgres_db
      - DB_NAME=meubanco
      - DB_USER=usuario
      - DB_PASSWORD=senha
    develop:
      watch:
        - action: sync
          path: ./curso_conteudo
          target: /code

  pagamento:
      build: ./pagamento
      ports:
        - "8003:5000"
      environment:
        - SECRET_KEY=minha-chave-supersegura
        - URL_CURSOS=http://curso_conteudo:5000
      depends_on:
        - curso_conteudo
        - db
      develop:
        watch:
          - action: sync
            path: ./pagamento
            target: /code
    
  redis:
    image: "redis:alpine"


volumes:
  pgdata: