services:
  auth:
    build: ./auth
    ports:
      - "8000:5000"
    environment:
      - SECRET_KEY=minha-chave-supersegura
    develop:
      watch:
        - action: sync
          path: ./auth
          target: /code
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    
  redis:
    image: "redis:alpine"


volumes:
  pgdata: