services:

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  database_service:
    build: ./database_service
    ports:
      - "8004:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DB_HOST=postgres_db
      - DB_NAME=meubanco
      - DB_USER=usuario
      - DB_PASSWORD=senha
      - DATABASE_SERVICE_URL=http://database_service:5000

  auth:
    build: ./auth
    ports:
      - "8000:5000"
    depends_on:
      - database_service
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DATABASE_SERVICE_URL=http://database_service:5000

  curso_conteudo:
    build: ./curso_conteudo
    ports:
      - "8002:5000"
    depends_on:
      - database_service
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DATABASE_SERVICE_URL=http://database_service:5000

  pagamento:
    build: ./pagamento
    ports:
      - "8003:5000"
    depends_on:
      - database_service
    environment:
      - SECRET_KEY=minha-chave-supersegura
      - DATABASE_SERVICE_URL=http://database_service:5000


volumes:
  pgdata: